/**
 * DEPRECATED ENTRY POINT — do not edit this file.
 *
 * The editor engine was split into ordered classic scripts under js/modules/.
 * Production loads them from TypoZen_Template.html; tests concat them via
 * tests/engine-source.mjs (and tests/build-test-template.mjs).
 *
 * See js/modules/load-order.json for the load order.
 *
 * This stub remains only so a grepped path "js/typozen.js" fails loudly rather than
 * silently shipping an abandoned monolith.
 */
throw new Error(
    'TypoZen: js/typozen.js is no longer the engine. Load js/modules/* in order ' +
    '(see js/modules/load-order.json and TypoZen_Template.html).'
);
